version: '3.7'
services:

  book-mysql-db:
    restart: always
    container_name: book-mysql-db
    image: 'mysql:8.0'
    command: [ "--max_connections=1000", "--default-authentication-plugin=mysql_native_password" ]
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ../book-database/src/main/resources/scripts/book_schema.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_ROOT_USERNAME --password=$$MYSQL_ROOT_PASSWORD
      timeout: 2s
      retries: 2

  ms-book-go-mux-gorm:
    build:
      context: ../ms-book-go-mux-gorm
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      book-mysql-db:
        condition: service_healthy
    ports:
      - "8080:8080"
