services:

  book-mysql-db:
    restart: always
    container_name: book-mysql-db
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ../book-database/src/main/resources/scripts/book_schema.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_ROOT_USERNAME --password=$$MYSQL_ROOT_PASSWORD
      timeout: 2s
      retries: 2

  ms-book-micronaut-reactive:
    image: joeltadeu/ms-book-micronaut-reactive
    container_name: ms-book-micronaut-reactive
    build:
      context: ../ms-book-micronaut-reactive
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      book-mysql-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - PROFILE=docker

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    links:
      - ms-book-micronaut-reactive

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    user: "104"
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./monitoring/grafana/config.monitoring